version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
  mongo_db:
    image: "mongo:4.4"
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
    ports:
      - 27017:27017